package com.wengu.app;

import androidx.test.platform.app.InstrumentationRegistry;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import java.io.*;
import org.json.*;

public final class AppSmokeTest {
    private Instrumentation instrument;
    private MainActivity activity;
    @Before public void isolateBackgroundBackup()throws Exception {
        instrument=InstrumentationRegistry.getInstrumentation();Context c=instrument.getTargetContext();LocalBackup.preferences(c).edit().clear().commit();androidx.work.WorkManager.getInstance(c).cancelAllWork().getResult().get(10,java.util.concurrent.TimeUnit.SECONDS);
        android.accessibilityservice.AccessibilityServiceInfo service=instrument.getUiAutomation().getServiceInfo();service.flags|=android.accessibilityservice.AccessibilityServiceInfo.FLAG_RETRIEVE_INTERACTIVE_WINDOWS|android.accessibilityservice.AccessibilityServiceInfo.FLAG_REPORT_VIEW_IDS|android.accessibilityservice.AccessibilityServiceInfo.FLAG_INCLUDE_NOT_IMPORTANT_VIEWS;instrument.getUiAutomation().setServiceInfo(service);
    }
    @After public void stopFixtureWorkAndActivities()throws Exception {
        Context c=InstrumentationRegistry.getInstrumentation().getTargetContext();LocalBackup.preferences(c).edit().putBoolean("enabled",false).commit();androidx.work.WorkManager.getInstance(c).cancelAllWork().getResult().get(10,java.util.concurrent.TimeUnit.SECONDS);
        instrument.runOnMainSync(()->{java.util.Set<Activity> ownActivities=new java.util.HashSet<>();for(androidx.test.runner.lifecycle.Stage stage:new androidx.test.runner.lifecycle.Stage[]{androidx.test.runner.lifecycle.Stage.CREATED,androidx.test.runner.lifecycle.Stage.STARTED,androidx.test.runner.lifecycle.Stage.RESUMED,androidx.test.runner.lifecycle.Stage.PAUSED,androidx.test.runner.lifecycle.Stage.STOPPED,androidx.test.runner.lifecycle.Stage.RESTARTED})ownActivities.addAll(androidx.test.runner.lifecycle.ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(stage));for(Activity a:ownActivities)if(a instanceof MainActivity&&!a.isDestroyed())a.finish();});instrument.waitForIdleSync();
    }
    private MainActivity launchFresh(Context c){
        // NEW_TASK alone can reuse a task still containing DocumentsUI after a failed test.
        // MonitoringInstrumentation then waits for an onCreate that never arrives. CLEAR_TASK
        // gives each launch its own fresh app lifecycle, including after the SAF regrant fixture.
        MainActivity fresh=(MainActivity)instrument.startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));instrument.waitForIdleSync();activity=fresh;instrument.runOnMainSync(()->refreshActivity());return activity;
    }
    private void refreshActivity(){for(Activity a:androidx.test.runner.lifecycle.ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(androidx.test.runner.lifecycle.Stage.RESUMED))if(a instanceof MainActivity)activity=(MainActivity)a;}
    private View find(View view,String label){if(view instanceof TextView&&label.equals(((TextView)view).getText().toString()))return view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){View result=find(group.getChildAt(i),label);if(result!=null)return result;}}return null;}
    private void click(String text){instrument.runOnMainSync(()->{refreshActivity();View view=find(activity.getWindow().getDecorView(),text);assertNotNull("Missing control "+text,view);view.performClick();});instrument.waitForIdleSync();}
    private void shot(String name)throws Exception {Thread.sleep(500);Bitmap b=instrument.getUiAutomation().takeScreenshot();assertNotNull(b);File folder=new File(instrument.getTargetContext().getExternalFilesDir(null),"qa");folder.mkdirs();try(OutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
    private void waitFor(String text)throws Exception {for(int i=0;i<40;i++){Thread.sleep(250);instrument.waitForIdleSync();final boolean[] found={false};instrument.runOnMainSync(()->{java.util.Collection<Activity> resumed=androidx.test.runner.lifecycle.ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(androidx.test.runner.lifecycle.Stage.RESUMED);refreshActivity();found[0]=activity!=null&&!activity.isDestroyed()&&resumed.contains(activity)&&find(activity.getWindow().getDecorView(),text)!=null;});if(found[0])return;}fail("Timeout waiting for resumed app control "+text);}
    @Test public void writePreviewApplyEditAndSettings()throws Exception {
        instrument=InstrumentationRegistry.getInstrumentation();Context c=instrument.getTargetContext();
        // This instance is dedicated to tests; only this app's data is reset.
        new Store(c).save(Store.fresh());c.getSharedPreferences(MainActivity.class.getSimpleName(),0).edit().clear().commit();
        WallpaperManager wm=WallpaperManager.getInstance(c);Bitmap baseline=Bitmap.createBitmap(720,1600,Bitmap.Config.ARGB_8888);baseline.eraseColor(0xFF445566);wm.setBitmap(baseline,null,true,1);wm.setBitmap(baseline,null,true,2);baseline.recycle();
        activity=launchFresh(c);instrument.runOnMainSync(()->assertNotNull(find(activity.getWindow().getDecorView(),"未设置本地备份  ›")));shot("01-today");
        click("＋ 写下第一条经验");
        instrument.runOnMainSync(()->{((EditText)activity.findViewById(MainActivity.ID_SUMMARY)).setText("不确定时，先做一次小规模验证。");((EditText)activity.findViewById(MainActivity.ID_BODY)).setText("做这个应用时，我先用自己的手机试用，再决定哪些功能值得继续投入。适合有想法却迟迟没有开始的时候。");});shot("02-editor");
        click("保存经验");waitFor("这条经验");instrument.runOnMainSync(()->assertNotNull("First saved experience should offer an unobtrusive backup entry",find(activity.getWindow().getDecorView(),"未设置本地备份  ›")));shot("03-detail");
        JSONObject data=new Store(c).load();assertEquals(1,Store.items(data).length());assertEquals(-1,Store.items(data).optJSONObject(0).optInt("stage"));
        click("预览并应用");shot("04-preview");
        // Engine calls the actual emulator WallpaperManager, preserving the other target.
        int oldHome=wm.getWallpaperId(1);
        final String id=Store.items(data).optJSONObject(0).optString("id");
        String status=new DeliveryEngine(c).apply(id,false,System.currentTimeMillis());assertTrue(status,status.contains("已应用"));
        assertEquals(oldHome,wm.getWallpaperId(1));assertTrue(wm.getWallpaperId(2)>0);
        assertEquals(0,Store.items(new Store(c).load()).optJSONObject(0).optInt("stage"));
        instrument.runOnMainSync(()->activity.onBackPressed());instrument.waitForIdleSync();instrument.runOnMainSync(()->activity.onBackPressed());instrument.waitForIdleSync();click("今日");shot("05-active");
        click("设置");shot("06-settings");click("锁屏和桌面");assertEquals(3,Store.settings(new Store(c).load()).optInt("target"));
        click("仅桌面");assertEquals(1,Store.settings(new Store(c).load()).optInt("target"));
        int oldLock=wm.getWallpaperId(2);new DeliveryEngine(c).apply(id,false,System.currentTimeMillis());assertEquals(oldLock,wm.getWallpaperId(2));assertTrue(wm.getWallpaperId(1)>0);
        click("仅锁屏");
        click("备份、恢复与运行状态");shot("07-data");
        // Activity recreation must preserve a partially typed draft.
        instrument.runOnMainSync(()->activity.onBackPressed());instrument.waitForIdleSync();click("经验库");click("＋ 记录");
        instrument.runOnMainSync(()->((EditText)activity.findViewById(MainActivity.ID_SUMMARY)).setText("先把问题写清楚，再寻找解决方法。"));
        instrument.runOnMainSync(()->activity.recreate());Thread.sleep(1500);
        assertEquals("先把问题写清楚，再寻找解决方法。",new JSONObject(c.getSharedPreferences(MainActivity.class.getSimpleName(),0).getString("draft","{}")).optString("summary"));
    }
    @Test public void photosBackupAndPrivacy()throws Exception {
        Context c=InstrumentationRegistry.getInstrumentation().getTargetContext();Store store=new Store(c);JSONObject state=Store.fresh(),item=Store.newExperience();Store.put(item,"summary","把注意力放回当下的一件事。");
        File input=new File(c.getCacheDir(),"sample-photo.png");Bitmap photo=Bitmap.createBitmap(720,1600,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(photo);Paint p=new Paint();p.setShader(new LinearGradient(0,0,720,1600,Color.WHITE,0xFF719473,Shader.TileMode.CLAMP));canvas.drawRect(0,0,720,1600,p);try(OutputStream out=new FileOutputStream(input)){photo.compress(Bitmap.CompressFormat.PNG,100,out);}photo.recycle();
        String ref=WallpaperComposer.importPhoto(c,android.net.Uri.fromFile(input));assertTrue(input.delete());assertTrue(store.photoFile(ref).isFile());Store.put(item,"photo",ref);Store.items(state).put(item);store.save(state);
        WallpaperComposer.Rendered rendered=WallpaperComposer.render(c,item,Store.settings(state),720,1600,2);assertFalse(rendered.photoFallback);File qa=new File(c.getExternalFilesDir(null),"qa");qa.mkdirs();try(OutputStream out=new FileOutputStream(new File(qa,"08-photo-wallpaper.png"))){rendered.bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}rendered.bitmap.recycle();
        ByteArrayOutputStream bytes=new ByteArrayOutputStream();Backup.export(c,bytes,false);Backup.ImportPlan plan=Backup.inspect(c,new ByteArrayInputStream(bytes.toByteArray()));assertEquals(1,plan.duplicates);Backup.restore(c,plan,0);assertEquals(1,Store.items(store.load()).length());
        DeliveryEngine engine=new DeliveryEngine(c);assertTrue(engine.apply(item.optString("id"),false,System.currentTimeMillis()).contains("已应用"));
        state=store.load();Store.put(Store.find(state,item.optString("id")),"private",true);store.save(state);assertTrue(engine.hide(item.optString("id")).contains("已清除"));assertEquals("",Store.session(store.load()).optString("current_id"));
        bytes=new ByteArrayOutputStream();Backup.export(c,bytes,false);plan=Backup.inspect(c,new ByteArrayInputStream(bytes.toByteArray()));assertEquals(0,plan.data.optJSONArray("items").length());plan.discard();
    }
    @Test public void manualNextButtonSwitchesAfterDailyNewLimit()throws Exception {
        instrument=InstrumentationRegistry.getInstrumentation();Context c=instrument.getTargetContext();Store store=new Store(c);
        JSONObject state=Store.fresh(),first=Store.newExperience(),second=Store.newExperience();Store.put(first,"summary","先写清问题，再开始行动。");Store.put(second,"summary","用一次小实验验证自己的判断。");
        Store.items(state).put(first).put(second);Store.put(Store.settings(state),"budget",1);Store.put(Store.settings(state),"new_limit",1);store.save(state);
        c.getSharedPreferences(MainActivity.class.getSimpleName(),0).edit().clear().putBoolean("visibility_understood",true).commit();
        WallpaperManager wm=WallpaperManager.getInstance(c);Bitmap baseline=Bitmap.createBitmap(720,1600,Bitmap.Config.ARGB_8888);baseline.eraseColor(0xFF445566);wm.setBitmap(baseline,null,true,1);wm.setBitmap(baseline,null,true,2);baseline.recycle();
        assertTrue(new DeliveryEngine(c).apply(first.optString("id"),false,System.currentTimeMillis()).contains("已应用"));int originalHome=wm.getWallpaperId(1),originalLock=wm.getWallpaperId(2);
        activity=launchFresh(c);
        click("立即换一条");waitFor(second.optString("summary"));state=store.load();assertEquals(second.optString("id"),Store.session(state).optString("current_id"));assertEquals(2,Store.session(state).optInt("new_count"));assertEquals(originalHome,wm.getWallpaperId(1));assertNotEquals(originalLock,wm.getWallpaperId(2));shot("09-manual-next-fixed");
        click("立即换一条");waitFor(first.optString("summary"));assertEquals(0,Store.find(store.load(),first.optString("id")).optInt("stage"));
    }
    @Test public void artworkSelectionAndInterfaceStylePersist()throws Exception {
        Context c=instrument.getTargetContext();Store store=new Store(c);JSONObject state=Store.fresh(),item=Store.newExperience();Store.put(item,"summary","给重要的事情，留一点安静的时间。");Store.items(state).put(item);Store.put(Store.settings(state),"target",3);store.save(state);c.getSharedPreferences(MainActivity.class.getSimpleName(),0).edit().clear().commit();
        activity=launchFresh(c);
        instrument.runOnMainSync(()->assertNull(find(activity.getWindow().getDecorView(),"让经验，在日常里重逢")));click("设置");click("文字提示");assertEquals("guided",Store.settings(store.load()).optString("ui_style"));instrument.runOnMainSync(()->assertNotNull(find(activity.getWindow().getDecorView(),"让经验，在日常里重逢")));shot("10-guided-settings");
        instrument.runOnMainSync(()->activity.recreate());Thread.sleep(1200);instrument.runOnMainSync(()->{refreshActivity();assertTrue(((RadioButton)activity.findViewById(302)).isChecked());});click("极简");assertEquals("minimal",Store.settings(store.load()).optString("ui_style"));shot("11-minimal-settings");
        click("经验库");instrument.runOnMainSync(()->{View summary=find(activity.getWindow().getDecorView(),item.optString("summary"));assertNotNull(summary);((View)summary.getParent()).performClick();});instrument.waitForIdleSync();click("预览并应用");
        click("预览锁屏");instrument.runOnMainSync(()->assertTrue(findPreview(activity.getWindow().getDecorView()).getContentDescription().toString().contains("锁屏预览示意")));shot("16-lock-preview-placeholders");click("预览桌面");instrument.runOnMainSync(()->assertTrue(findPreview(activity.getWindow().getDecorView()).getContentDescription().toString().contains("桌面壁纸预览")));shot("17-home-preview");click("预览锁屏");
        for(int theme=6;theme<=8;theme++) {
            final String label=WallpaperComposer.THEME_NAMES[theme];instrument.runOnMainSync(()->{View title=find(activity.getWindow().getDecorView(),label);assertNotNull(title);assertEquals(label,((View)title.getParent()).getContentDescription().toString());assertTrue(((View)title.getParent()).performClick());assertTrue("Selected artwork needs a visible selection state",((View)title.getParent()).isSelected());for(int other=6;other<=8;other++)if(!label.equals(WallpaperComposer.THEME_NAMES[other]))assertFalse(((View)find(activity.getWindow().getDecorView(),WallpaperComposer.THEME_NAMES[other]).getParent()).isSelected());});instrument.waitForIdleSync();shot("12-artwork-"+theme);
            WallpaperComposer.Rendered rendered=WallpaperComposer.render(c,item,withTheme(Store.settings(store.load()),theme),720,1600,2);assertFalse(rendered.photoFallback);File qa=new File(c.getExternalFilesDir(null),"qa");qa.mkdirs();try(OutputStream out=new FileOutputStream(new File(qa,"13-bundled-"+theme+".png"))){assertTrue(rendered.bitmap.compress(Bitmap.CompressFormat.PNG,100,out));}rendered.bitmap.recycle();
        }
    }
    private LockScreenPreview findPreview(View view){if(view instanceof LockScreenPreview)return (LockScreenPreview)view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){LockScreenPreview found=findPreview(group.getChildAt(i));if(found!=null)return found;}}return null;}
    private JSONObject withTheme(JSONObject cfg,int theme){JSONObject copy=Store.copy(cfg);Store.put(copy,"theme",theme);Store.put(copy,"photo","");return copy;}
    // Uses the actual Android DocumentsUI and external-storage provider, with a fixture-only folder.
    @Test public void publicLocalBackupsSurviveLostAppStateAndRestoreThroughUi()throws Exception {
        Context c=instrument.getTargetContext();Store store=new Store(c);JSONObject state=Store.fresh(),item=Store.newExperience(),secret=Store.newExperience();Store.put(item,"summary","先把经验留下，再慢慢理解它。");Store.put(secret,"summary","为自己的边界留出空间。");Store.put(secret,"private",true);Store.put(secret,"body","私密经验也需要本地备份。");Store.items(state).put(item).put(secret);Store.put(Store.settings(state),"ui_style","minimal");
        String photoRef="photos/"+java.util.UUID.randomUUID()+".jpg";File originalPhoto=store.photoFile(photoRef);originalPhoto.getParentFile().mkdirs();Bitmap sample=Bitmap.createBitmap(40,80,Bitmap.Config.ARGB_8888);sample.eraseColor(0xFF597765);try(OutputStream out=new FileOutputStream(originalPhoto)){assertTrue(sample.compress(Bitmap.CompressFormat.JPEG,90,out));}sample.recycle();byte[] photoBytes=java.nio.file.Files.readAllBytes(originalPhoto.toPath());Store.put(item,"photo",photoRef);store.save(state);
        // Keep the fixture name short enough to remain unambiguous in DocumentsUI's grid.
        String folder="WQA-"+java.util.UUID.randomUUID().toString().substring(0,5);shell("mkdir -p /sdcard/Documents/"+folder);android.os.Bundle status=new android.os.Bundle();status.putString("backup_test_folder","/sdcard/Documents/"+folder);instrument.sendStatus(0,status);
        c.getSharedPreferences(MainActivity.class.getSimpleName(),0).edit().clear().commit();activity=launchFresh(c);click("设置");click("本地备份与恢复");selectBackupFolder(folder);waitFor("立即备份");
        assertTrue(LocalBackup.configured(c));assertTrue(LocalBackup.enabled(c));assertTrue(LocalBackup.preferences(c).getBoolean("include_private",true));assertEquals("已备份",LocalBackup.summary(c));assertTrue(LocalBackup.coverageCurrent(c));android.net.Uri tree=android.net.Uri.parse(LocalBackup.preferences(c).getString("tree",""));assertTrue(c.getContentResolver().getPersistedUriPermissions().stream().anyMatch(grant->grant.getUri().equals(tree)&&grant.isReadPermission()&&grant.isWritePermission()));
        java.util.List<LocalBackup.Snapshot> versions=LocalBackup.list(c);assertEquals(1,versions.size());try(InputStream in=c.getContentResolver().openInputStream(versions.get(0).uri)){Backup.ImportPlan initial=Backup.inspect(c,in);assertEquals(2,initial.data.optJSONArray("items").length());initial.discard();}
        // Stop deferred work so only the explicit fixture saves below create versions.
        LocalBackup.preferences(c).edit().putBoolean("enabled",false).commit();androidx.work.WorkManager.getInstance(c).cancelUniqueWork("wengu-local-backup").getResult().get(10,java.util.concurrent.TimeUnit.SECONDS);assertEquals("备份已暂停",LocalBackup.summary(c));assertTrue("Pausing future backups does not discard an already confirmed snapshot",LocalBackup.coverageCurrent(c));
        state=store.load();long confirmedRevision=Store.revision(state);Store.put(Store.session(state),"status","只更新运行状态");Store.log(state,"attempt","","仅日志变化");store.save(state);assertEquals(confirmedRevision,Store.revision(store.load()));assertTrue("Session/log changes must not dirty exported data",LocalBackup.coverageCurrent(c));
        android.net.Uri deletedBackup=android.net.Uri.parse(LocalBackup.preferences(c).getString("last_uri",""));String deletedId=android.provider.DocumentsContract.getDocumentId(deletedBackup);assertTrue("Delete only this test's own generated backup",deletedId.startsWith("primary:Documents/"+folder+"/"));assertEquals(versions.get(0).uri,deletedBackup);assertTrue(android.provider.DocumentsContract.deleteDocument(c.getContentResolver(),deletedBackup));LocalBackup.verifyAvailable(c);assertFalse(LocalBackup.coverageCurrent(c));assertFalse(LocalBackup.preferences(c).getBoolean("backed_known",true));assertTrue(LocalBackup.preferences(c).getString("error","").contains("备份文件不可用"));assertEquals("备份已暂停 · 上次备份失败",LocalBackup.summary(c));assertFalse(LocalBackup.enabled(c));assertTrue(LocalBackup.write(c).contains("已备份"));assertTrue("A real replacement ZIP must acknowledge the current revision again",LocalBackup.coverageCurrent(c));assertFalse(LocalBackup.preferences(c).contains("error"));assertEquals("备份已暂停",LocalBackup.summary(c));assertEquals(1,LocalBackup.list(c).size());
        // Deliberate clearing on this confirmed installation is distinct from reinstalling.
        // Preserve the full historic ZIP, then repair only the subsequent empty snapshot.
        JSONObject savedRecords=Store.copy(store.load());String sameInstallation=Store.epoch(savedRecords);android.net.Uri fullHistory=android.net.Uri.parse(LocalBackup.preferences(c).getString("last_uri",""));assertFalse(LocalBackup.preferences(c).getBoolean("restore_confirmed",false));JSONObject deliberatelyEmpty=Store.copy(savedRecords);Store.put(deliberatelyEmpty,"items",new JSONArray());store.save(deliberatelyEmpty);assertEquals(sameInstallation,Store.epoch(store.load()));assertTrue(LocalBackup.write(c).contains("已备份"));assertTrue(LocalBackup.coverageCurrent(c));assertFalse(LocalBackup.preferences(c).getBoolean("awaiting_restore",false));android.net.Uri emptySnapshot=android.net.Uri.parse(LocalBackup.preferences(c).getString("last_uri",""));assertTrue(android.provider.DocumentsContract.getDocumentId(emptySnapshot).startsWith("primary:Documents/"+folder+"/"));assertNotEquals(fullHistory,emptySnapshot);try(InputStream in=c.getContentResolver().openInputStream(emptySnapshot)){Backup.ImportPlan empty=Backup.inspect(c,in);assertEquals(0,empty.data.optJSONArray("items").length());empty.discard();}assertTrue(android.provider.DocumentsContract.deleteDocument(c.getContentResolver(),emptySnapshot));LocalBackup.verifyAvailable(c);assertFalse(LocalBackup.coverageCurrent(c));assertFalse(LocalBackup.preferences(c).getBoolean("backed_known",true));assertTrue("Repairing an acknowledged empty snapshot must not be mistaken for reinstall recovery",LocalBackup.write(c).contains("已备份"));assertFalse(LocalBackup.preferences(c).getBoolean("awaiting_restore",false));assertTrue(LocalBackup.coverageCurrent(c));assertEquals(sameInstallation,Store.epoch(store.load()));try(InputStream in=c.getContentResolver().openInputStream(fullHistory)){Backup.ImportPlan preserved=Backup.inspect(c,in);assertEquals(2,preserved.data.optJSONArray("items").length());preserved.discard();}store.save(savedRecords);LocalBackup.write(c);assertEquals(2,Store.items(store.load()).length());assertTrue(LocalBackup.coverageCurrent(c));
        android.net.Uri parent=android.provider.DocumentsContract.buildDocumentUriUsingTree(tree,android.provider.DocumentsContract.getTreeDocumentId(tree));android.net.Uri unrelated=android.provider.DocumentsContract.createDocument(c.getContentResolver(),parent,"text/plain","notes-to-keep.txt");assertNotNull(unrelated);try(OutputStream out=c.getContentResolver().openOutputStream(unrelated)){out.write("Unrelated fixture: preserve this file.".getBytes(java.nio.charset.StandardCharsets.UTF_8));}
        for(int version=1;version<=11;version++){state=store.load();Store.put(Store.find(state,item.optString("id")),"body","本地备份版本 "+version);store.save(state);assertFalse("An edited revision must not inherit an older backup's coverage",LocalBackup.coverageCurrent(c));assertTrue(LocalBackup.write(c).contains("已备份"));assertTrue(LocalBackup.coverageCurrent(c));assertEquals(Store.revision(store.load()),LocalBackup.preferences(c).getLong("backed_revision",-1));}
        LocalBackup.preferences(c).edit().putBoolean("enabled",true).putBoolean("include_private",false).commit();assertEquals("有未备份内容",LocalBackup.summary(c));LocalBackup.write(c);assertEquals("非私密已备份 · 私密未备份",LocalBackup.summary(c));assertFalse(LocalBackup.coverageCurrent(c));java.util.List<LocalBackup.Snapshot> nonPrivate=LocalBackup.list(c);try(InputStream in=c.getContentResolver().openInputStream(nonPrivate.get(0).uri)){Backup.ImportPlan excluded=Backup.inspect(c,in);assertEquals(1,excluded.data.optJSONArray("items").length());excluded.discard();}LocalBackup.preferences(c).edit().putBoolean("include_private",true).commit();assertFalse(LocalBackup.coverageCurrent(c));LocalBackup.write(c);assertEquals("已备份",LocalBackup.summary(c));assertTrue(LocalBackup.coverageCurrent(c));LocalBackup.preferences(c).edit().putBoolean("enabled",false).commit();
        versions=LocalBackup.list(c);assertEquals(10,versions.size());try(InputStream in=c.getContentResolver().openInputStream(unrelated)){assertNotNull(in);assertTrue(in.read()!=-1);}String newestName=versions.get(0).name;byte[] newestBytes;try(InputStream in=c.getContentResolver().openInputStream(versions.get(0).uri)){newestBytes=read(in);}assertEquals("本地备份已是最新",LocalBackup.write(c));assertEquals(10,LocalBackup.list(c).size());shot("14-local-backup");
        // Uninstallation revokes SAF grants and deletes private app state; reproduce both before regrant.
        c.getContentResolver().releasePersistableUriPermission(tree,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);LocalBackup.verifyAvailable(c);assertFalse(LocalBackup.coverageCurrent(c));assertTrue(LocalBackup.preferences(c).getString("error","").contains("权限失效"));LocalBackup.preferences(c).edit().clear().commit();store.save(Store.fresh());assertTrue(originalPhoto.delete());assertFalse(LocalBackup.configured(c));
        activity=launchFresh(c);click("设置");click("本地备份与恢复");selectBackupFolder(folder);uiWait("找到之前的本地备份");assertTrue(LocalBackup.preferences(c).getBoolean("awaiting_restore",false));assertFalse(LocalBackup.enabled(c));assertEquals("待恢复历史备份",LocalBackup.summary(c));assertFalse(LocalBackup.coverageCurrent(c));assertEquals(10,LocalBackup.list(c).size());
        try(InputStream in=c.getContentResolver().openInputStream(LocalBackup.list(c).get(0).uri)){assertArrayEquals("Empty app state must not overwrite a historical backup",newestBytes,read(in));}
        uiClick("选择恢复版本");uiWait(newestName);uiClick(newestName);uiWait("恢复备份");uiClick("恢复");waitFor("我的经验");JSONObject restored=store.load();assertEquals(2,Store.items(restored).length());assertTrue(Store.find(restored,secret.optString("id")).optBoolean("private"));assertEquals(secret.optString("body"),Store.find(restored,secret.optString("id")).optString("body"));assertEquals("本地备份版本 11",Store.find(restored,item.optString("id")).optString("body"));assertArrayEquals(photoBytes,java.nio.file.Files.readAllBytes(store.photoFile(Store.find(restored,item.optString("id")).optString("photo")).toPath()));assertFalse(Store.settings(restored).optBoolean("enabled"));assertFalse(LocalBackup.preferences(c).getBoolean("awaiting_restore",false));assertTrue(LocalBackup.enabled(c));assertTrue(LocalBackup.coverageCurrent(c));assertEquals("已备份",LocalBackup.summary(c));shot("15-restored-experiences");
        // Reconfirm the already verified restoration so a persisted confirmation exists.
        // Losing the private Store must invalidate this installation-bound acknowledgement.
        LocalBackup.preferences(c).edit().putBoolean("enabled",false).commit();androidx.work.WorkManager.getInstance(c).cancelAllWork().getResult().get(10,java.util.concurrent.TimeUnit.SECONDS);LocalBackup.confirmRestore(c);assertTrue(LocalBackup.preferences(c).getBoolean("restore_confirmed",false));assertFalse(LocalBackup.enabled(c));assertEquals(Store.epoch(store.load()),LocalBackup.preferences(c).getString("restore_epoch",""));java.util.List<String> protectedVersions=new java.util.ArrayList<>();for(LocalBackup.Snapshot snapshot:LocalBackup.list(c))protectedVersions.add(snapshot.name+"|"+snapshot.uri);
        synchronized(Store.LOCK){File appFiles=c.getFilesDir().getCanonicalFile(),lostData=new File(appFiles,"experiences.json").getCanonicalFile();assertEquals("experiences.json",lostData.getName());assertEquals("Delete only the dedicated test app's exact private data file",appFiles,lostData.getParentFile());assertFalse("A recovery copy would make this a different scenario",new File(lostData+".bak").exists());assertTrue(lostData.isFile());assertTrue(lostData.delete());}
        try{LocalBackup.write(c);fail("A stale restore confirmation must not permit an empty backup after private data loss");}catch(IOException expected){assertTrue(expected.getMessage(),expected.getMessage().contains("恢复"));}assertTrue(LocalBackup.preferences(c).getBoolean("awaiting_restore",false));assertFalse(LocalBackup.coverageCurrent(c));java.util.List<String> remainingVersions=new java.util.ArrayList<>();for(LocalBackup.Snapshot snapshot:LocalBackup.list(c))remainingVersions.add(snapshot.name+"|"+snapshot.uri);assertEquals("Losing private data must not create or prune public historical backups",protectedVersions,remainingVersions);
    }
    @Test public void changingTargetRequiresImmediateApplyAndPreservesPauseAndReview()throws Exception {
        Context c=instrument.getTargetContext();Store store=new Store(c);JSONObject state=Store.fresh(),item=Store.newExperience();long now=System.currentTimeMillis(),due=java.time.LocalDate.now().plusDays(10).toEpochDay();Store.put(item,"summary","给每一次调整，留出验证结果的时间。");Store.put(item,"stage",2);Store.put(item,"due",due);Store.put(item,"last_success",now-3*24*60*60_000L);Store.items(state).put(item);store.save(state);c.getSharedPreferences(MainActivity.class.getSimpleName(),0).edit().clear().putBoolean("visibility_understood",true).commit();
        WallpaperManager wm=WallpaperManager.getInstance(c);Bitmap baseline=Bitmap.createBitmap(720,1600,Bitmap.Config.ARGB_8888);baseline.eraseColor(0xFF445566);wm.setBitmap(baseline,null,true,1);wm.setBitmap(baseline,null,true,2);baseline.recycle();assertTrue(new DeliveryEngine(c).apply(item.optString("id"),false,now).contains("已应用"));state=store.load();JSONObject original=Store.copy(Store.find(state,item.optString("id")));Store.put(Store.settings(state),"enabled",false);store.save(state);int homeBefore=wm.getWallpaperId(1),lockBefore=wm.getWallpaperId(2);
        activity=launchFresh(c);click("设置");click("仅桌面");assertEquals(2,Store.session(store.load()).optInt("current_targets"));assertEquals(homeBefore,wm.getWallpaperId(1));assertEquals(lockBefore,wm.getWallpaperId(2));instrument.runOnMainSync(()->assertNotNull(find(activity.getWindow().getDecorView(),"新设置尚待应用")));click("今日");instrument.runOnMainSync(()->{assertNotNull(find(activity.getWindow().getDecorView(),"已应用 · 仅锁屏"));assertNotNull(find(activity.getWindow().getDecorView(),"待应用 · 仅桌面"));});shot("18-target-awaiting-apply");
        click("立即应用当前设置");waitFor("已应用 · 仅桌面");assertNotEquals(homeBefore,wm.getWallpaperId(1));assertEquals(lockBefore,wm.getWallpaperId(2));assertFalse(Store.settings(store.load()).optBoolean("enabled"));assertEquals(1,Store.session(store.load()).optInt("current_targets"));JSONObject after=Store.find(store.load(),item.optString("id"));assertEquals(2,after.optInt("stage"));assertEquals(due,after.optLong("due"));assertEquals(original.optLong("last_success"),after.optLong("last_success"));assertEquals(original.optLong("last_displayed"),after.optLong("last_displayed"));shot("19-target-applied-still-paused");
        homeBefore=wm.getWallpaperId(1);click("设置");click("仅锁屏");click("立即应用到锁屏");waitFor("已应用 · 仅锁屏");assertEquals(homeBefore,wm.getWallpaperId(1));assertNotEquals(lockBefore,wm.getWallpaperId(2));assertFalse(Store.settings(store.load()).optBoolean("enabled"));assertEquals(original.optLong("last_displayed"),Store.find(store.load(),item.optString("id")).optLong("last_displayed"));
    }
    private byte[] read(InputStream in)throws Exception {assertNotNull(in);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);return out.toByteArray();}
    private void shell(String command)throws Exception {try(android.os.ParcelFileDescriptor descriptor=instrument.getUiAutomation().executeShellCommand(command);InputStream in=new android.os.ParcelFileDescriptor.AutoCloseInputStream(descriptor)){read(in);}}
    private android.view.accessibility.AccessibilityNodeInfo uiFind(android.view.accessibility.AccessibilityNodeInfo node,String label){if(node==null)return null;String text=node.getText()==null?"":node.getText().toString().trim(),description=node.getContentDescription()==null?"":node.getContentDescription().toString().trim();if(node.isVisibleToUser()&&(label.equalsIgnoreCase(text)||label.equalsIgnoreCase(description)||label.startsWith("WQA-")&&(description.contains(label)||text.contains(label))))return node;for(int i=0;i<node.getChildCount();i++){android.view.accessibility.AccessibilityNodeInfo match=uiFind(node.getChild(i),label);if(match!=null)return match;}return null;}
    private java.util.List<android.view.accessibility.AccessibilityNodeInfo> uiRoots(){java.util.List<android.view.accessibility.AccessibilityNodeInfo> roots=new java.util.ArrayList<>();android.app.UiAutomation automation=instrument.getUiAutomation();android.view.accessibility.AccessibilityNodeInfo active=automation.getRootInActiveWindow();if(active!=null)roots.add(active);for(android.view.accessibility.AccessibilityWindowInfo window:automation.getWindows())if(window.isActive()||window.isFocused()){android.view.accessibility.AccessibilityNodeInfo root=window.getRoot();if(root!=null)roots.add(root);}return roots;}
    private android.view.accessibility.AccessibilityNodeInfo uiSearch(String... labels){for(android.view.accessibility.AccessibilityNodeInfo root:uiRoots())for(String label:labels){android.view.accessibility.AccessibilityNodeInfo match=uiFind(root,label);if(match!=null)return match;}return null;}
    private String uiDescription(){StringBuilder result=new StringBuilder();for(android.view.accessibility.AccessibilityNodeInfo root:uiRoots())describeUi(root,result,0);return result.length()==0?"No active or interactive window roots":result.toString();}
    private void describeUi(android.view.accessibility.AccessibilityNodeInfo node,StringBuilder result,int depth){if(node==null||depth>30||result.length()>8000)return;result.append("\n").append(node.getViewIdResourceName()).append(" text=").append(node.getText()).append(" description=").append(node.getContentDescription());for(int i=0;i<node.getChildCount();i++)describeUi(node.getChild(i),result,depth+1);}
    private void uiWait(String label)throws Exception {uiWaitAny(label);}
    private void uiWaitAny(String... labels)throws Exception {for(int i=0;i<60;i++){if(uiSearch(labels)!=null)return;Thread.sleep(250);}fail("System UI missing "+java.util.Arrays.toString(labels)+"; "+uiDescription());}
    private void uiClick(String label)throws Exception {uiClickAny(label);}
    private void uiClickAny(String... labels)throws Exception {uiWaitAny(labels);android.view.accessibility.AccessibilityNodeInfo node=uiSearch(labels);while(node!=null&&!node.isClickable())node=node.getParent();assertNotNull("No clickable ancestor for "+java.util.Arrays.toString(labels),node);assertTrue("System UI disabled "+java.util.Arrays.toString(labels),node.isEnabled());assertTrue("System click failed "+java.util.Arrays.toString(labels),node.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK));Thread.sleep(300);instrument.waitForIdleSync();}
    private void selectBackupFolder(String folder)throws Exception {click("选择本地备份文件夹");uiClick(folder);uiClickAny("Use this folder","使用這個資料夾","使用此文件夹","使用这个文件夹","使用這個文件夾");uiClickAny("Allow","允許","允许");}
}
