package com.wengu.app;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
    static final int BG=0xFFF5F4EF,INK=0xFF21372D,GREEN=0xFF315D4C,MUTED=0xFF748075,LINE=0xFFE1E5DC,PALE=0xFFE7EDE3;
    static final int PICK_PHOTO=21,EXPORT_BACKUP=22,IMPORT_BACKUP=23,EXPORT_WALL=24,PICK_BACKUP_FOLDER=25;
    private static final ExecutorService IO=Executors.newSingleThreadExecutor();
    private String page="today",detailId="",query="",filter="all",tagFilter="",photoDestination="";
    private boolean sortByDue=false,moreEditor=false;
    private JSONObject state,draft,styleDraft;
    private LinearLayout root,content,bottom;
    private ScrollView scroll;
    private LockScreenPreview styleImage;
    private Button previewLockButton,previewHomeButton;
    private int previewTarget=0;
    private final List<LinearLayout> artworkTiles=new ArrayList<>();
    private TextView backupLine;
    private final Handler statusHandler=new Handler(Looper.getMainLooper());
    private final Runnable backupRefresh=new Runnable(){public void run(){if(backupLine!=null){backupLine.setText(LocalBackup.summary(MainActivity.this)+"  ›");backupLine.setTextColor(LocalBackup.coverageCurrent(MainActivity.this)&&LocalBackup.enabled(MainActivity.this)?MUTED:GREEN);}statusHandler.postDelayed(this,3000);}};
    private boolean includePrivate=false,busy=false;
    private Backup.ImportPlan importPlan;
    private Bitmap exportBitmap,previewBitmap;
    private long lastResumeCheck=0;
    public static final int ID_SUMMARY=101,ID_BODY=102,ID_SAVE=103,ID_NEW=104;

    @Override public void onCreate(Bundle saved){super.onCreate(saved);
        if(saved!=null){page=saved.getString("page","today");detailId=saved.getString("detail","");query=saved.getString("query","");filter=saved.getString("filter","all");photoDestination=saved.getString("photo_destination","");draft=parse(saved.getString("draft"));styleDraft=parse(saved.getString("style"));}
        else {draft=parse(getPreferences(MODE_PRIVATE).getString("draft",null));}
        if(saved!=null){tagFilter=saved.getString("tag_filter","");sortByDue=saved.getBoolean("sort_due",false);}
        try{state=new Store(this).load();}catch(Exception e){new AlertDialog.Builder(this).setTitle("保留你的经验数据").setMessage(e.getMessage()).setPositiveButton("关闭",(d,w)->finish()).setCancelable(false).show();return;}
        render();DisplayWorker.schedule(this);
    }
    @Override protected void onResume(){super.onResume();statusHandler.removeCallbacks(backupRefresh);statusHandler.post(backupRefresh);if(state!=null&&!busy&&System.currentTimeMillis()-lastResumeCheck>60000){lastResumeCheck=System.currentTimeMillis();IO.execute(()->{LocalBackup.verifyAvailable(this);try{new DeliveryEngine(this).apply(null,true,System.currentTimeMillis());}catch(Exception ignored){}runOnUiThread(()->{if(!isDestroyed()&&("today".equals(page)||"backup".equals(page))&&!busy)render();});});}}
    @Override protected void onPause(){super.onPause();statusHandler.removeCallbacks(backupRefresh);if(draft!=null)getPreferences(MODE_PRIVATE).edit().putString("draft",draft.toString()).commit();}
    @Override protected void onDestroy(){statusHandler.removeCallbacks(backupRefresh);if(previewBitmap!=null){previewBitmap.recycle();previewBitmap=null;}super.onDestroy();}
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putString("page",page);out.putString("detail",detailId);out.putString("query",query);out.putString("filter",filter);out.putString("tag_filter",tagFilter);out.putBoolean("sort_due",sortByDue);out.putString("photo_destination",photoDestination);if(draft!=null)out.putString("draft",draft.toString());if(styleDraft!=null)out.putString("style",styleDraft.toString());}
    private JSONObject parse(String s){try{return s==null?null:new JSONObject(s);}catch(Exception e){return null;}}
    int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
    TextView text(String value,float size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(dp(3),1);return t;}
    TextView title(String value){TextView t=text(value,25,INK);t.setTypeface(null,Typeface.BOLD);return t;}
    GradientDrawable surface(int color,int border,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(border!=0)d.setStroke(dp(1),border);return d;}
    LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    void gap(LinearLayout target,int height){target.addView(new View(this),new LinearLayout.LayoutParams(1,dp(height)));}
    boolean minimal(){return state==null||!"guided".equals(Store.settings(state).optString("ui_style","minimal"));}
    void hint(LinearLayout target,String value){if(minimal())return;TextView t=text(value,13,MUTED);target.addView(t);gap(target,8);}
    LinearLayout card(){LinearLayout l=column();l.setPadding(dp(18),dp(18),dp(18),dp(18));l.setBackground(surface(Color.WHITE,LINE,20));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(14);content.addView(l,lp);return l;}
    Button button(String label,boolean primary,Runnable action){Button b=new Button(this);b.setText(label);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(primary?Color.WHITE:GREEN);b.setTypeface(null,Typeface.BOLD);b.setBackground(surface(primary?GREEN:PALE,0,13));b.setPadding(dp(15),dp(8),dp(15),dp(8));b.setMinHeight(dp(48));b.setMinimumHeight(dp(48));b.setOnClickListener(v->{if(!busy)action.run();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.topMargin=dp(8);b.setLayoutParams(lp);return b;}
    void twoButtons(LinearLayout target,String a,Runnable aa,String b,Runnable bb){LinearLayout r=row();Button left=button(a,false,aa),right=button(b,true,bb);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(50),1);lp.rightMargin=dp(8);r.addView(left,lp);r.addView(right,new LinearLayout.LayoutParams(0,dp(50),1));gap(target,10);target.addView(r);}
    private void render(){if(isDestroyed())return;try{state=new Store(this).load();}catch(Exception e){message(e.getMessage());return;}
        backupLine=null;
        if(previewBitmap!=null){previewBitmap.recycle();previewBitmap=null;}
        root=column();root.setBackgroundColor(BG);setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());root.setPadding(i.left,i.top,i.right,i.bottom);}else{root.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());}return insets;});
        scroll=new ScrollView(this);scroll.setFillViewport(true);content=column();content.setPadding(dp(20),dp(20),dp(20),dp(24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        boolean top="today".equals(page)||"library".equals(page)||"settings".equals(page);
        if(top){LinearLayout header=row();TextView brand=title("温故");header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));header.addView(text(LocalDate.now().format(DateTimeFormatter.ofPattern("M月d日")),13,MUTED));content.addView(header);gap(content,5);hint(content,"让经验，在日常里重逢");gap(content,14);}
        else {TextView back=text("‹  返回",16,GREEN);back.setPadding(0,dp(5),0,dp(12));back.setOnClickListener(v->back());content.addView(back);}
        switch(page){case "today":today();break;case "library":library();break;case "settings":settingsPage();break;case "edit":editor();break;case "detail":detail();break;case "style":style();break;case "data":dataPage();break;case "backup":backupPage();break;}
        if(top){bottom=row();bottom.setPadding(dp(14),dp(8),dp(14),dp(8));bottom.setBackground(surface(Color.WHITE,LINE,0));for(String[] tab:new String[][]{{"today","今日"},{"library","经验库"},{"settings","设置"}}){TextView t=text(tab[1],15,page.equals(tab[0])?GREEN:MUTED);t.setGravity(Gravity.CENTER);t.setTypeface(null,page.equals(tab[0])?Typeface.BOLD:Typeface.NORMAL);t.setBackground(surface(page.equals(tab[0])?PALE:Color.WHITE,0,14));bottom.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));t.setOnClickListener(v->{page=tab[0];render();});}root.addView(bottom);}
    }
    private void minimalToday(){
        JSONObject cfg=Store.settings(state),session=Store.session(state),current=Store.find(state,session.optString("current_id"));
        LinearLayout line=row();line.addView(text(appliedLocation(session),14,MUTED),new LinearLayout.LayoutParams(0,-2,1));TextView status=text(cfg.optBoolean("enabled")?"● 自动已开启":"○ 暂停",13,GREEN);line.addView(status);content.addView(line);gap(content,24);
        if(current==null){LinearLayout empty=card();empty.addView(text("留下一句话",28,INK));gap(empty,10);Button add=button("＋ 写下第一条经验",true,()->newEntry());add.setId(ID_NEW);empty.addView(add);}
        else {LinearLayout hero=card();gap(hero,22);TextView quote=text(current.optString("summary"),28,INK);quote.setTypeface(null,Typeface.BOLD);balanceText(quote);hero.addView(quote);gap(hero,28);hero.addView(button("查看经历",false,()->openDetail(current.optString("id"))));}
        if(current!=null&&session.optInt("current_targets")!=cfg.optInt("target",2)){content.addView(text("待应用 · "+targetLabel(cfg.optInt("target",2)),13,GREEN));content.addView(button("立即应用当前设置",true,()->applyCurrentSettings()));}
        if(session.optLong("last_success")>0)content.addView(text("上次成功 · "+dateTime(session.optLong("last_success")),12,MUTED));
        String result=session.optString("status");if(hasDisplayIssue(session)||result.contains("只有一条")||result.contains("没有可展示"))content.addView(text(result,13,MUTED));
        if(hasDisplayIssue(session)){TextView fix=text("查看运行状态与处理方法  ›",13,GREEN);fix.setPadding(0,dp(10),0,dp(10));fix.setOnClickListener(v->{page="data";render();});content.addView(fix);}
        long next=ReviewPlanner.nextAttempt(state,System.currentTimeMillis(),ZoneId.systemDefault());if(next>0){gap(content,7);content.addView(text("下次尝试 · "+dateTime(next),12,MUTED));}
        twoButtons(content,cfg.optBoolean("enabled")?"暂停自动展示":"开启自动展示",()->toggleAutomatic(),"立即换一条",()->apply(null));
        backupIndicator(content);
    }
    private void backupIndicator(LinearLayout parent){gap(parent,14);backupLine=text(LocalBackup.summary(this)+"  ›",13,LocalBackup.coverageCurrent(this)&&LocalBackup.enabled(this)?MUTED:GREEN);backupLine.setPadding(0,dp(12),0,dp(12));backupLine.setMinHeight(dp(48));backupLine.setOnClickListener(v->{page="backup";render();});parent.addView(backupLine);}
    private String appliedLocation(JSONObject session){if(session.optString("current_id").isEmpty()||session.optLong("last_success")==0)return "尚未应用壁纸";return "已应用 · "+targetLabel(session.optInt("current_targets",2));}
    private boolean hasDisplayIssue(JSONObject session){String message=session.optString("status");return session.optJSONObject("pending")!=null||message.contains("失败")||message.contains("受限")||message.contains("不允许")||message.contains("已改变")||message.contains("未完成")||message.contains("未排入");}
    // Layout's API 23 constant is the same value as the API 29 LineBreaker alias.
    @android.annotation.SuppressLint("WrongConstant")
    private void balanceText(TextView quote){quote.setBreakStrategy(Layout.BREAK_STRATEGY_BALANCED);}
    private void today(){if(minimal()){minimalToday();return;}content.addView(title("今天，让旧经验再次出现"));gap(content,14);
        JSONObject cfg=Store.settings(state),s=Store.session(state),current=Store.find(state,s.optString("current_id"));
        LinearLayout status=card();status.addView(text(cfg.optBoolean("enabled")?"自动展示已开启":"自动展示已暂停",16,GREEN));gap(status,5);status.addView(text(appliedLocation(s),14,GREEN));status.addView(text(s.optString("status"),13,MUTED));if(s.optLong("last_success")>0)status.addView(text("上次成功 · "+dateTime(s.optLong("last_success")),12,MUTED));if(current!=null&&s.optInt("current_targets")!=cfg.optInt("target",2))status.addView(button("立即应用当前设置",true,()->applyCurrentSettings()));
        long next=ReviewPlanner.nextAttempt(state,System.currentTimeMillis(),ZoneId.systemDefault());if(next>0){gap(status,6);status.addView(text("计划下次尝试  "+dateTime(next),13,MUTED));}
        if(current!=null){LinearLayout hero=card();hero.addView(text("正在展示",12,MUTED));gap(hero,12);TextView quote=text(current.optString("summary"),23,INK);quote.setTypeface(null,Typeface.BOLD);hero.addView(quote);gap(hero,10);hero.addView(text("反复遇见，让这句话唤起当时的经验。",13,MUTED));
            hero.addView(button("查看背景与原来的经历",false,()->openDetail(current.optString("id"))));
        }else {LinearLayout hero=card();hero.addView(text("一句话，留下自己的理解",23,INK));gap(hero,10);hero.addView(text("记录一条生活、学习或工作的经验，预览后把它放到手机壁纸上。",15,MUTED));Button b=button("＋ 写下第一条经验",true,()->newEntry());b.setId(ID_NEW);hero.addView(b);}
        List<JSONObject> candidates=ReviewPlanner.candidates(state,System.currentTimeMillis(),ZoneId.systemDefault());LinearLayout plan=card();plan.addView(text("今天的展示安排",17,INK));gap(plan,8);
        JSONArray shown=s.optJSONArray("shown");plan.addView(text("今天已展示 "+(shown==null?0:shown.length())+" 条 · 自动展示上限 "+cfg.optInt("budget",4)+" 条",14,MUTED));
        if(candidates.isEmpty()){gap(plan,8);plan.addView(text(current==null?"写下经验并应用后，这里会显示你的展示安排。":"暂时没有新到期的经验，当前内容会继续陪伴你。",14,MUTED));}
        else for(int i=0;i<Math.min(4,candidates.size());i++){JSONObject e=candidates.get(i);gap(plan,10);TextView item=text((i+1)+"  "+e.optString("summary"),15,INK);plan.addView(item);item.setOnClickListener(v->openDetail(e.optString("id")));}
        twoButtons(content,cfg.optBoolean("enabled")?"暂停自动展示":"开启自动展示",()->toggleAutomatic(),"立即换一条",()->apply(null));
        backupIndicator(content);
        hint(content,"自动展示时每张至少保留两小时，系统省电可能延后执行。手动换一条可立即切换，不受每日数量上限限制。");
    }
    private void newEntry(){if(draft!=null&&!draft.optString("summary").isEmpty()){new AlertDialog.Builder(this).setTitle("有一条未保存的经验").setMessage("继续上次的草稿，或重新写一条。") .setPositiveButton("继续草稿",(d,w)->{page="edit";render();}).setNegativeButton("重新写",(d,w)->{draft=Store.newExperience();page="edit";render();}).show();}else{draft=Store.newExperience();page="edit";render();}}
    private void openDetail(String id){detailId=id;page="detail";render();}
    private void library(){LinearLayout heading=row();heading.addView(title("我的经验"),new LinearLayout.LayoutParams(0,-2,1));Button add=button("＋ 记录",true,()->newEntry());add.setId(ID_NEW);heading.addView(add,new LinearLayout.LayoutParams(dp(100),dp(45)));content.addView(heading);gap(content,14);
        EditText search=field(null,"搜索总结、背景或标签",query,null);search.setSingleLine(true);content.addView(search);gap(content,10);
        HorizontalScrollView filters=new HorizontalScrollView(this);filters.setHorizontalScrollBarEnabled(false);LinearLayout chips=row();for(String[] f:new String[][]{{"all","全部"},{"active","参与展示"},{"paused","暂停"},{"archived","归档"},{"private","私密"}}){TextView t=text(f[1],13,filter.equals(f[0])?Color.WHITE:GREEN);t.setPadding(dp(13),dp(9),dp(13),dp(9));t.setBackground(surface(filter.equals(f[0])?GREEN:PALE,0,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.rightMargin=dp(7);chips.addView(t,lp);t.setOnClickListener(v->{filter=f[0];render();});}filters.addView(chips);content.addView(filters);gap(content,14);
        Set<String> allTags=new TreeSet<>();for(int i=0;i<Store.items(state).length();i++){JSONArray tags=Store.items(state).optJSONObject(i).optJSONArray("tags");if(tags!=null)for(int j=0;j<tags.length();j++)allTags.add(tags.optString(j));}
        if(!allTags.isEmpty()){HorizontalScrollView tagScroll=new HorizontalScrollView(this);tagScroll.setHorizontalScrollBarEnabled(false);LinearLayout tagRow=row();List<String> choices=new ArrayList<>();choices.add("");choices.addAll(allTags);for(String tag:choices){TextView chip=text(tag.isEmpty()?"所有标签":"# "+tag,12,tag.equals(tagFilter)?Color.WHITE:GREEN);chip.setPadding(dp(11),dp(7),dp(11),dp(7));chip.setBackground(surface(tag.equals(tagFilter)?GREEN:PALE,0,14));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.rightMargin=dp(7);tagRow.addView(chip,lp);chip.setOnClickListener(v->{tagFilter=tag;render();});}tagScroll.addView(tagRow);content.addView(tagScroll);gap(content,10);}
        TextView order=text(sortByDue?"到期优先  ↓  点击切换":"最近修改  ↓  点击切换",12,GREEN);order.setPadding(0,dp(5),0,dp(12));content.addView(order);order.setOnClickListener(v->{sortByDue=!sortByDue;render();});
        LinearLayout list=column();content.addView(list);fillLibrary(list);
        search.addTextChangedListener(new SimpleWatcher(){public void afterTextChanged(Editable e){query=e.toString();fillLibrary(list);}});
    }
    private void fillLibrary(LinearLayout list){list.removeAllViews();List<JSONObject> items=new ArrayList<>();JSONArray arr=Store.items(state);
        for(int i=0;i<arr.length();i++){JSONObject e=arr.optJSONObject(i);boolean match="all".equals(filter)||"private".equals(filter)&&e.optBoolean("private")||filter.equals(e.optString("status"));boolean tagged=tagFilter.isEmpty();JSONArray tags=e.optJSONArray("tags");if(tags!=null)for(int j=0;j<tags.length();j++)if(tagFilter.equals(tags.optString(j)))tagged=true;String hay=e.optString("summary")+" "+e.optString("body")+" "+e.optString("scenario")+" "+e.optJSONArray("tags");if(match&&tagged&&hay.toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT)))items.add(e);}
        if(sortByDue)items.sort(Comparator.comparingLong((JSONObject e)->e.optLong("due")).thenComparing(e->!e.optBoolean("important")));else items.sort(Comparator.comparingLong((JSONObject e)->e.optLong("modified")).reversed());
        if(items.isEmpty()){TextView empty=text(query.isEmpty()?"这里还没有经验。写下你想经常想起的一句话。":"没有找到相符的经验。",16,MUTED);empty.setPadding(dp(10),dp(28),dp(10),dp(28));list.addView(empty);}
        for(JSONObject e:items){LinearLayout card=column();card.setPadding(dp(17),dp(17),dp(17),dp(17));card.setBackground(surface(Color.WHITE,LINE,18));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(12);list.addView(card,lp);TextView summary=text(e.optString("summary"),18,INK);summary.setTypeface(null,Typeface.BOLD);card.addView(summary);gap(card,9);card.addView(text(statusLabel(e)+"  ·  "+dueLabel(e),12,MUTED));JSONArray tags=e.optJSONArray("tags");if(tags!=null&&tags.length()>0){gap(card,5);card.addView(text(tagsText(tags),12,GREEN));}card.setOnClickListener(v->openDetail(e.optString("id")));}
    }
    private void detail(){JSONObject e=Store.find(state,detailId);if(e==null){page="library";render();return;}content.addView(title("这条经验"));gap(content,14);LinearLayout quote=card();quote.addView(text(e.optString("summary"),24,INK));gap(quote,10);quote.addView(text(statusLabel(e)+"  ·  "+dueLabel(e),13,MUTED));if(e.optJSONArray("tags")!=null&&!tagsText(e.optJSONArray("tags")).isEmpty()){gap(quote,6);quote.addView(text(tagsText(e.optJSONArray("tags")),13,GREEN));}
        section("背后的经历与道理",e.optString("body"));section("适用场景",e.optString("scenario"));section("例外与更新",e.optString("exception"));
        twoButtons(content,"编辑经验",()->{draft=Store.copy(e);page="edit";render();},"预览并应用",()->{styleDraft=Store.copy(Store.settings(state));page="style";render();});
        backupIndicator(content);if(Store.items(state).length()==1&&!LocalBackup.configured(this))content.addView(text("选择一次文件夹，之后保存经验会自动备份。",12,MUTED));
        if(minimal()){content.addView(button("更多操作",false,()->entryActions(e)));return;}
        content.addView(button("active".equals(e.optString("status"))?"暂停这条经验":"恢复参与展示",false,()->mutateItem(detailId,item->Store.put(item,"status","active".equals(item.optString("status"))?"paused":"active"),false)));
        content.addView(button("archived".equals(e.optString("status"))?"取消归档":"归档这条经验",false,()->mutateItem(detailId,item->Store.put(item,"status","archived".equals(item.optString("status"))?"active":"archived"),false)));
        content.addView(button("重新开始间隔展示",false,()->new AlertDialog.Builder(this).setTitle("重新开始这条经验？").setMessage("保留内容，清零展示阶段，按照正常每日预算重新安排。") .setPositiveButton("重新开始",(d,w)->mutateItem(detailId,item->{Store.put(item,"stage",-1);Store.put(item,"due",LocalDate.now().toEpochDay());Store.put(item,"last_success",0);},false)).setNegativeButton("取消",null).show()));
        content.addView(button("删除经验",false,()->new AlertDialog.Builder(this).setTitle("删除这条经验？").setMessage("如果它正在壁纸上显示，应用会尝试清除正文。删除后无法撤销，请先备份需要保留的内容。") .setPositiveButton("删除",(d,w)->mutateItem(detailId,item->{},true)).setNegativeButton("取消",null).show()));
    }
    private void entryActions(JSONObject e){String[] actions={"active".equals(e.optString("status"))?"暂停这条经验":"恢复参与展示","archived".equals(e.optString("status"))?"取消归档":"归档这条经验","重新开始间隔展示","删除经验"};new AlertDialog.Builder(this).setTitle("这条经验").setItems(actions,(dialog,index)->{if(index==0)mutateItem(detailId,item->Store.put(item,"status","active".equals(item.optString("status"))?"paused":"active"),false);if(index==1)mutateItem(detailId,item->Store.put(item,"status","archived".equals(item.optString("status"))?"active":"archived"),false);if(index==2)new AlertDialog.Builder(this).setTitle("重新开始展示？").setPositiveButton("重新开始",(d,w)->mutateItem(detailId,item->{Store.put(item,"stage",-1);Store.put(item,"due",LocalDate.now().toEpochDay());Store.put(item,"last_success",0);},false)).setNegativeButton("取消",null).show();if(index==3)new AlertDialog.Builder(this).setTitle("删除这条经验？").setMessage("删除后无法撤销。").setPositiveButton("删除",(d,w)->mutateItem(detailId,item->{},true)).setNegativeButton("取消",null).show();}).show();}
    private void section(String label,String value){if(value.isEmpty())return;LinearLayout box=card();box.addView(text(label,14,GREEN));gap(box,8);TextView body=text(value,16,INK);body.setTextIsSelectable(true);box.addView(body);}
    interface ItemEdit {void change(JSONObject item);}
    private void mutateItem(String id,ItemEdit edit,boolean delete){runIO("正在保存",()->{Store store=new Store(this);boolean hide=false;synchronized(Store.LOCK){JSONObject data=store.load(),e=Store.find(data,id);if(e==null)return "经验不存在";edit.change(e);Store.put(e,"modified",System.currentTimeMillis());Store.put(e,"version",e.optInt("version",1)+1);hide=delete||e.optBoolean("private");if(delete){for(int i=0;i<Store.items(data).length();i++)if(id.equals(Store.items(data).optJSONObject(i).optString("id"))){Store.items(data).remove(i);break;}}store.save(data);store.collectPhotos(data);}return hide?new DeliveryEngine(this).hide(id):"已保存";},()->{if(delete)page="library";render();});}
    private EditText field(LinearLayout parent,String hint,String value,String key){EditText e=new EditText(this);e.setTextSize(16);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint(hint);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setGravity(Gravity.TOP);e.setBackground(surface(Color.WHITE,LINE,12));e.setText(value);e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);if(key!=null)e.addTextChangedListener(new SimpleWatcher(){public void afterTextChanged(Editable value){if(draft!=null)Store.put(draft,key,value.toString());}});if(parent!=null){parent.addView(e,new LinearLayout.LayoutParams(-1,-2));gap(parent,14);}return e;}
    private void editor(){if(draft==null)draft=Store.newExperience();content.addView(title(Store.find(state,draft.optString("id"))==null?"写下一条经验":"修改这条经验"));gap(content,8);hint(content,"一句话总结，保留能唤起经历的关键词。建议 15—50 字。");
        content.addView(text(minimal()?"一句话":"一句话总结 · 必填",14,GREEN));gap(content,7);EditText summary=field(content,minimal()?"你想再次想起的道理":"例如：不确定时，先做一次小规模验证。",draft.optString("summary"),"summary");summary.setId(ID_SUMMARY);summary.setMinLines(3);
        TextView count=text(WallpaperComposer.graphemes(draft.optString("summary"))+" / 120 字",12,MUTED);content.addView(count);summary.addTextChangedListener(new SimpleWatcher(){public void afterTextChanged(Editable e){count.setText(WallpaperComposer.graphemes(e.toString())+" / 120 字");}});gap(content,13);
        content.addView(text(minimal()?"背景 · 可选":"背后的经历与道理",14,GREEN));gap(content,7);EditText body=field(content,minimal()?"当时发生了什么":"事情经过、为什么有效、你当时的理解……",draft.optString("body"),"body");body.setId(ID_BODY);body.setMinLines(minimal()?2:4);
        LinearLayout advanced=column();if(minimal()){Button more=button(moreEditor?"收起选项":"更多选项",false,()->{});more.setOnClickListener(v->{moreEditor=!moreEditor;advanced.setVisibility(moreEditor?View.VISIBLE:View.GONE);more.setText(moreEditor?"收起选项":"更多选项");});content.addView(more);}content.addView(advanced);advanced.setVisibility(!minimal()||moreEditor?View.VISIBLE:View.GONE);
        field(advanced,"适用场景（可选，最多 200 字）",draft.optString("scenario"),"scenario");field(advanced,"例外与后续更新（可选，最多 500 字）",draft.optString("exception"),"exception");
        EditText tags=field(advanced,"标签，用逗号分隔",tagsText(draft.optJSONArray("tags")),null);tags.setSingleLine(true);tags.addTextChangedListener(new SimpleWatcher(){public void afterTextChanged(Editable e){JSONArray values=new JSONArray();Set<String> unique=new LinkedHashSet<>();for(String s:e.toString().split("[,，、\\s]+"))if(!s.trim().isEmpty())unique.add(s.trim());for(String s:unique)values.put(s);Store.put(draft,"tags",values);}});
        checkbox(advanced,minimal()?"重要":"重要经验（同到期时优先）",draft.optBoolean("important"),v->Store.put(draft,"important",v));checkbox(advanced,minimal()?"私密 · 不用于壁纸":"私密经验（不用于壁纸）",draft.optBoolean("private"),v->Store.put(draft,"private",v));
        gap(advanced,10);hint(advanced,"此条背景："+(draft.optString("photo").isEmpty()?draft.optInt("theme",-1)<0?"跟随全局设置":WallpaperComposer.THEME_NAMES[Math.floorMod(draft.optInt("theme"),WallpaperComposer.THEME_NAMES.length)]:"专属照片"));
        twoButtons(advanced,"选择专属照片",()->choosePhoto("entry"),"跟随全局背景",()->{Store.put(draft,"photo","");Store.put(draft,"theme",-1);render();});
        Button save=button("保存经验",true,()->saveEntry());save.setId(ID_SAVE);content.addView(save);hint(content,"保存经验不会立即改变系统壁纸，预览后可主动应用。");
    }
    private void saveEntry(){try{WallpaperComposer.validate(draft);}catch(Exception e){message(e.getMessage());return;}JSONObject saved=Store.copy(draft);runIO("正在保存",()->{Store store=new Store(this);boolean hide=false;synchronized(Store.LOCK){JSONObject data=store.load(),existing=Store.find(data,saved.optString("id"));hide=saved.optBoolean("private")&&existing!=null;Store.put(saved,"modified",System.currentTimeMillis());if(existing!=null){Store.put(saved,"version",existing.optInt("version",1)+1);for(int i=0;i<Store.items(data).length();i++)if(saved.optString("id").equals(Store.items(data).optJSONObject(i).optString("id"))){Store.items(data).remove(i);break;}}Store.items(data).put(saved);Store.log(data,"saved",saved.optString("id"),"success");store.save(data);}return hide?new DeliveryEngine(this).hide(saved.optString("id")):"经验已保存";},()->{detailId=saved.optString("id");draft=null;getPreferences(MODE_PRIVATE).edit().remove("draft").apply();hideKeyboard();page="detail";render();});}
    interface BoolChange{void changed(boolean value);}
    private void checkbox(LinearLayout target,String label,boolean value,BoolChange cb){CheckBox b=new CheckBox(this);b.setText(label);b.setTextSize(14);b.setTextColor(INK);b.setChecked(value);b.setOnCheckedChangeListener((v,checked)->cb.changed(checked));target.addView(b);}
    private void style(){if(styleDraft==null)styleDraft=Store.copy(Store.settings(state));JSONObject selected=Store.find(state,detailId);if(selected==null){for(int i=0;i<Store.items(state).length();i++){JSONObject e=Store.items(state).optJSONObject(i);if(Store.eligible(e)){selected=e;detailId=e.optString("id");break;}}}
        content.addView(title("壁纸预览"));gap(content,8);hint(content,"正文默认位于画面中下部，避开锁屏时钟。以手机实际显示为准。");
        if(selected!=null&&(!selected.optString("photo").isEmpty()||selected.optInt("theme",-1)>=0))content.addView(text("这条经验使用专属背景，可在编辑页改为跟随全局背景。",12,GREEN));
        int configuredTarget=styleDraft.optInt("target",2);if(configuredTarget!=3)previewTarget=configuredTarget;else if(previewTarget!=1&&previewTarget!=2)previewTarget=2;
        previewLockButton=null;previewHomeButton=null;
        if(configuredTarget==3){LinearLayout controls=row();previewLockButton=button("预览锁屏",previewTarget==2,()->{previewTarget=2;refreshPreview();});previewHomeButton=button("预览桌面",previewTarget==1,()->{previewTarget=1;refreshPreview();});LinearLayout.LayoutParams left=new LinearLayout.LayoutParams(0,dp(50),1);left.rightMargin=dp(8);controls.addView(previewLockButton,left);controls.addView(previewHomeButton,new LinearLayout.LayoutParams(0,dp(50),1));gap(content,10);content.addView(controls);markPreviewTarget();}
        LinearLayout preview=card();styleImage=new LockScreenPreview(this);preview.addView(styleImage,new LinearLayout.LayoutParams(-1,dp(350)));preview.addView(text("时钟与通知仅为占位示意",11,MUTED));refreshPreview();
        artworkTiles.clear();LinearLayout themes=card();themes.addView(text("内置壁纸",17,INK));gap(themes,10);LinearLayout gallery=row();themes.addView(gallery);for(int i=6;i<9;i++){final int index=i;LinearLayout tile=column();tile.setPadding(dp(4),dp(4),dp(4),0);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(3),0,dp(3),0);gallery.addView(tile,lp);ImageView thumb=new ImageView(this);thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);try{thumb.setImageBitmap(WallpaperComposer.builtInImage(this,index,180,400));}catch(Exception ignored){}tile.addView(thumb,new LinearLayout.LayoutParams(-1,dp(145)));TextView label=text(WallpaperComposer.THEME_NAMES[i],12,GREEN);label.setGravity(Gravity.CENTER);label.setPadding(0,dp(8),0,dp(8));tile.addView(label);tile.setOnClickListener(v->{Store.put(styleDraft,"theme",index);Store.put(styleDraft,"photo","");refreshPreview();});tile.setContentDescription(WallpaperComposer.THEME_NAMES[i]);artworkTiles.add(tile);}markSelectedArtwork();
        for(int r=0;r<2;r++){LinearLayout colors=row();themes.addView(colors);for(int j=0;j<3;j++){final int index=r*3+j;Button choice=button(WallpaperComposer.THEME_NAMES[index],false,()->{Store.put(styleDraft,"theme",index);Store.put(styleDraft,"photo","");refreshPreview();});choice.setTextSize(12);choice.setPadding(dp(3),0,dp(3),0);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(43),1);lp.setMargins(dp(3),dp(7),dp(3),0);colors.addView(choice,lp);}}
        themes.addView(button("选择照片背景",false,()->choosePhoto("style")));checkbox(themes,"自动轮换内置背景",styleDraft.optBoolean("random"),v->{Store.put(styleDraft,"random",v);refreshPreview();});
        LinearLayout typography=card();typography.addView(text("文字与位置",17,INK));slider(typography,"字号",22,40,styleDraft.optInt("font",28),v->{Store.put(styleDraft,"font",v);refreshPreview();});slider(typography,"锁屏文字位置",35,75,styleDraft.optInt("lock_y",56),v->{Store.put(styleDraft,"lock_y",v);refreshPreview();});slider(typography,"桌面文字位置",35,75,styleDraft.optInt("home_y",50),v->{Store.put(styleDraft,"home_y",v);refreshPreview();});slider(typography,"遮罩强度",0,100,styleDraft.optInt("scrim",55),v->{Store.put(styleDraft,"scrim",v);refreshPreview();});checkbox(typography,"使用深色文字",styleDraft.optBoolean("dark_text"),v->{Store.put(styleDraft,"dark_text",v);refreshPreview();});checkbox(typography,"使用衬线字体",styleDraft.optBoolean("serif"),v->{Store.put(styleDraft,"serif",v);refreshPreview();});
        hint(content,"照片和背景改动不重置经验的展示阶段。此条的专属背景优先于全局背景。");
        twoButtons(content,"保存样式",()->saveStyle(false),"应用这条壁纸",()->saveStyle(true));content.addView(button("导出壁纸图片",false,()->exportWallpaper()));
    }
    private void refreshPreview(){if(styleImage==null||styleDraft==null)return;JSONObject e=Store.find(state,detailId);if(e==null){e=Store.newExperience();Store.put(e,"summary","把每一次经历，留下一个能重新想起的道理。");}final JSONObject item=e;
        try{int[] actual=DeliveryEngine.size(this);int target=styleDraft.optInt("target",2)==3?previewTarget:styleDraft.optInt("target",2);WallpaperComposer.Rendered r=WallpaperComposer.render(this,item,styleDraft,540,Math.round(540f*actual[1]/actual[0]),target);styleImage.setPreview(r.bitmap,target,item.optString("summary"));if(previewBitmap!=null)previewBitmap.recycle();previewBitmap=r.bitmap;markSelectedArtwork();markPreviewTarget();}
        catch(Exception error){styleImage.clearPreview(error.getMessage());Toast.makeText(this,error.getMessage(),Toast.LENGTH_SHORT).show();}
    }
    private void markPreviewTarget(){Button[] controls={previewLockButton,previewHomeButton};for(int i=0;i<controls.length;i++){Button control=controls[i];if(control==null)continue;boolean selected=previewTarget==(i==0?2:1);control.setSelected(selected);control.setBackground(surface(selected?GREEN:PALE,0,12));control.setTextColor(selected?Color.WHITE:GREEN);}}
    private void markSelectedArtwork(){if(styleDraft==null)return;JSONObject item=Store.find(state,detailId);boolean itemBackground=item!=null&&(!item.optString("photo").isEmpty()||item.optInt("theme",-1)>=0);boolean selectedPhoto=!styleDraft.optString("photo").isEmpty();int selected=styleDraft.optInt("theme",6);for(int i=0;i<artworkTiles.size();i++){LinearLayout tile=artworkTiles.get(i);boolean chosen=!itemBackground&&!selectedPhoto&&selected==i+6;tile.setSelected(chosen);tile.setBackground(surface(chosen?PALE:Color.WHITE,chosen?GREEN:LINE,10));}}
    interface IntChange{void changed(int value);}
    private void slider(LinearLayout target,String label,int min,int max,int value,IntChange cb){gap(target,13);TextView caption=text(label+"  "+value,14,INK);target.addView(caption);SeekBar seek=new SeekBar(this);seek.setMax(max-min);seek.setProgress(Math.max(0,Math.min(max-min,value-min)));target.addView(seek,new LinearLayout.LayoutParams(-1,dp(45)));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean user){caption.setText(label+"  "+(p+min));if(user)cb.changed(p+min);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});}
    private void saveStyle(boolean apply){JSONObject cfg=Store.copy(styleDraft);runIO("正在保存样式",()->{synchronized(Store.LOCK){Store store=new Store(this);JSONObject data=store.load();Store.put(cfg,"enabled",Store.settings(data).optBoolean("enabled"));Store.put(data,"settings",cfg);store.save(data);}return "壁纸样式已保存";},()->{if(apply)apply(detailId);else render();});}
    private void choosePhoto(String destination){photoDestination=destination;Intent i=new Intent(Build.VERSION.SDK_INT>=33?"android.provider.action.PICK_IMAGES":Intent.ACTION_OPEN_DOCUMENT);if(Build.VERSION.SDK_INT<33){i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");}else i.setType("image/*");try{startActivityForResult(i,PICK_PHOTO);}catch(Exception e){Intent fallback=new Intent(Intent.ACTION_OPEN_DOCUMENT);fallback.addCategory(Intent.CATEGORY_OPENABLE);fallback.setType("image/*");startActivityForResult(fallback,PICK_PHOTO);}}
    private void settingsPage(){content.addView(title(minimal()?"设置":"按自己的节奏温故"));gap(content,14);JSONObject cfg=Store.settings(state);
        LinearLayout appearance=card();appearance.addView(text("界面风格",17,INK));RadioGroup styles=new RadioGroup(this);styles.setOrientation(LinearLayout.HORIZONTAL);for(String[] style:new String[][]{{"minimal","极简"},{"guided","文字提示"}}){RadioButton radio=new RadioButton(this);radio.setText(style[1]);radio.setTextColor(INK);radio.setId("minimal".equals(style[0])?301:302);styles.addView(radio,new RadioGroup.LayoutParams(0,dp(48),1));radio.setChecked(minimal()=="minimal".equals(style[0]));}appearance.addView(styles);styles.setOnCheckedChangeListener((group,id)->{try{synchronized(Store.LOCK){Store store=new Store(this);JSONObject data=store.load();Store.put(Store.settings(data),"ui_style",id==301?"minimal":"guided");store.save(data);}render();}catch(Exception e){message(e.getMessage());}});
        content.addView(button("本地备份与恢复",true,()->{page="backup";render();}));gap(content,14);
        LinearLayout target=card();target.addView(text("壁纸显示位置",17,INK));RadioGroup group=new RadioGroup(this);for(int[] option:new int[][]{{2,0},{1,1},{3,2}}){RadioButton rb=new RadioButton(this);rb.setId(200+option[0]);rb.setText(targetLabel(option[0]));rb.setTextColor(INK);rb.setPadding(0,dp(7),0,dp(7));group.addView(rb);if(option[0]==cfg.optInt("target",2))rb.setChecked(true);}target.addView(group);group.setOnCheckedChangeListener((g,id)->{changeSetting("target",id-200);render();});target.addView(text(appliedLocation(Store.session(state)),12,MUTED));JSONObject current=Store.find(state,Store.session(state).optString("current_id"));if(Store.eligible(current)){if(Store.session(state).optInt("current_targets")!=cfg.optInt("target",2))target.addView(text("新设置尚待应用",12,GREEN));target.addView(button("立即应用到"+(cfg.optInt("target",2)==1?"桌面":cfg.optInt("target",2)==2?"锁屏":"锁屏和桌面"),true,()->applyCurrentSettings()));}else target.addView(text("先保存一条经验，再预览并应用。",12,MUTED));
        target.addView(text("仅更新所选位置，其他壁纸保留。",12,MUTED));
        LinearLayout schedule=card();schedule.addView(text("每日自动展示数量",17,INK));slider(schedule,"最多展示",1,8,cfg.optInt("budget",4),v->changeSetting("budget",v));slider(schedule,"最多加入新经验",0,3,cfg.optInt("new_limit",1),v->changeSetting("new_limit",v));
        hint(schedule,"优先安排到期经验；有积压时暂缓加入新经验。同一条当天只推进一次。上限用于自动展示，手动可额外切换；手动展示也计入当天数量。活跃时段不足时会顺延。");
        content.addView(button("设置活跃时段 · "+String.format(Locale.ROOT,"%02d:00—%02d:00",cfg.optInt("start_hour",8),cfg.optInt("end_hour",22)),false,()->chooseHours()));
        if(!minimal()){LinearLayout intervals=card();intervals.addView(text("自动间隔展示",17,INK));gap(intervals,8);intervals.addView(text("1 → 3 → 7 → 14 → 30 → 60 天",17,GREEN));gap(intervals,7);hint(intervals,"每次完整应用后，从实际日期计算下一次间隔；最后阶段每 60 天再次出现。展示不代表已经记住，无需打卡或评分。");}
        content.addView(button("调整壁纸背景与文字",false,()->{detailId=Store.session(state).optString("current_id");styleDraft=Store.copy(Store.settings(state));page="style";render();}));
        content.addView(button(cfg.optBoolean("enabled")?"暂停自动展示":"开启自动展示",true,()->toggleAutomatic()));
        content.addView(button("备份、恢复与运行状态",false,()->{page="data";render();}));
        if(!minimal()){LinearLayout local=card();local.addView(text("个人经验，保存在你的手机",17,INK));gap(local,7);hint(local,"无需登录，离线可用，照片保存在应用内。本地备份设置后会自动保存。温故 0.3.0");}else{gap(content,12);content.addView(text("温故 0.3.0",12,MUTED));}
    }
    private void changeSetting(String key,int value){try{synchronized(Store.LOCK){Store store=new Store(this);JSONObject data=store.load();Store.put(Store.settings(data),key,value);store.save(data);state=data;}DisplayWorker.reschedule(this);}catch(Exception e){message(e.getMessage());}}
    private void chooseHours(){LinearLayout box=column();box.setPadding(dp(20),dp(10),dp(20),0);NumberPicker start=new NumberPicker(this),end=new NumberPicker(this);start.setMinValue(0);start.setMaxValue(22);start.setValue(Store.settings(state).optInt("start_hour",8));end.setMinValue(1);end.setMaxValue(24);end.setValue(Store.settings(state).optInt("end_hour",22));LinearLayout r=row();r.addView(start,new LinearLayout.LayoutParams(0,dp(120),1));r.addView(end,new LinearLayout.LayoutParams(0,dp(120),1));box.addView(text("开始小时                       结束小时",14,MUTED));box.addView(r);AlertDialog d=new AlertDialog.Builder(this).setTitle("活跃时段").setView(box).setPositiveButton("保存",null).setNegativeButton("取消",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{if(end.getValue()-start.getValue()<2){message("活跃时段至少保留两小时");return;}changeSetting("start_hour",start.getValue());changeSetting("end_hour",end.getValue());d.dismiss();render();}));d.show();}
    private void toggleAutomatic(){JSONObject cfg=Store.settings(state);if(cfg.optBoolean("enabled")){runIO("暂停展示",()->{synchronized(Store.LOCK){Store store=new Store(this);JSONObject data=store.load();Store.put(Store.settings(data),"enabled",false);Store.put(Store.session(data),"status","已暂停，保留当前壁纸");store.save(data);}DisplayWorker.schedule(this);return "自动展示已暂停";},()->render());}
        else {boolean any=false;for(int i=0;i<Store.items(state).length();i++)if(Store.eligible(Store.items(state).optJSONObject(i)))any=true;if(!any){message("请先添加一条参与展示的非私密经验");return;}runIO("开启自动展示",()->{synchronized(Store.LOCK){Store store=new Store(this);JSONObject data=store.load();Store.put(Store.settings(data),"enabled",true);Store.put(Store.session(data),"status","自动展示已开启，等待下一有效时段");Store.session(data).remove("owned_1");Store.session(data).remove("owned_2");store.save(data);}DisplayWorker.reschedule(this);return "自动展示已开启";},()->render());}}
    private void apply(String id){if(!getPreferences(MODE_PRIVATE).getBoolean("visibility_understood",false)){new AlertDialog.Builder(this).setTitle("这句话会显示在手机屏幕上").setMessage("任何能看见你手机屏幕的人，都可能读到壁纸上的总结。私密经验不会用于壁纸。") .setPositiveButton("明白并应用",(d,w)->{getPreferences(MODE_PRIVATE).edit().putBoolean("visibility_understood",true).apply();performApply(id);}).setNegativeButton("取消",null).show();}else performApply(id);}
    private void performApply(String id){runIO("正在生成并应用壁纸",()->new DeliveryEngine(this).apply(id,false,System.currentTimeMillis()),()->{page="today";render();});}
    private void applyCurrentSettings(){runIO("正在应用当前设置",()->new DeliveryEngine(this).applyCurrentSettings(System.currentTimeMillis()),()->render());}
    private void dataPage(){content.addView(title("数据与运行状态"));gap(content,14);LinearLayout backup=card();backup.addView(text("备份你的经验",18,INK));gap(backup,8);hint(backup,"导出 ZIP 备份，包含经验、展示进度和照片副本。请保存到你信任的位置。默认不包含私密经验。");checkbox(backup,"此次备份包含私密经验",includePrivate,v->includePrivate=v);backup.addView(button("导出备份",true,()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"温故备份-"+LocalDate.now()+".zip");startActivityForResult(i,EXPORT_BACKUP);}));backup.addView(button("从备份恢复",false,()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,IMPORT_BACKUP);}));
        backup.addView(button("本地自动备份",false,()->{page="backup";render();}));
        LinearLayout diagnostic=card();diagnostic.addView(text("自动展示状态",18,INK));gap(diagnostic,8);JSONObject s=Store.session(state);diagnostic.addView(text(s.optString("status"),14,INK));gap(diagnostic,8);diagnostic.addView(text("上次成功："+(s.optLong("last_success")==0?"尚未应用":dateTime(s.optLong("last_success"))),13,MUTED));diagnostic.addView(text("Android "+Build.VERSION.RELEASE+" · "+Build.MANUFACTURER+" "+Build.MODEL,13,MUTED));
        try{WallpaperManager wm=WallpaperManager.getInstance(this);diagnostic.addView(text("系统壁纸能力："+(wm.isWallpaperSupported()&&wm.isSetWallpaperAllowed()?"可用":"受限"),13,MUTED));}catch(Exception ignored){}
        diagnostic.addView(text("后台最近检查："+(s.optLong("last_worker")==0?"尚无运行记录":dateTime(s.optLong("last_worker"))),13,MUTED));
        if(s.optJSONObject("pending")!=null){String pendingId=s.optJSONObject("pending").optString("experience_id");diagnostic.addView(button("重试未完成的应用",true,()->apply(pendingId)));}
        else if(Store.settings(state).optBoolean("enabled"))diagnostic.addView(button("检查并重新安排自动展示",false,()->runIO("正在检查自动展示",()->{DisplayWorker.reschedule(this);return new DeliveryEngine(this).apply(null,true,System.currentTimeMillis());},()->render())));
        else diagnostic.addView(button("开启自动展示",true,()->toggleAutomatic()));
        diagnostic.addView(button("打开系统应用设置",false,()->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))));
        LinearLayout help=card();help.addView(text("小米手机后台运行",18,INK));gap(help,8);help.addView(text("在系统中为温故允许后台自启动，并将应用省电策略设为允许后台运行／无限制。不同系统版本的入口名称可能不同。\n\n如果你修改了系统壁纸，温故会暂停自动覆盖。可以回到这里重新开启。强行停止后，请重新打开应用。",14,MUTED));
        JSONArray events=state.optJSONArray("events");if(events!=null&&events.length()>0){LinearLayout logs=card();logs.addView(text("最近运行记录",17,INK));for(int i=events.length()-1;i>=Math.max(0,events.length()-8);i--){JSONObject e=events.optJSONObject(i);gap(logs,8);logs.addView(text(dateTime(e.optLong("time"))+" · "+eventLabel(e.optString("type"))+"\n"+eventResult(e),12,MUTED));}}
    }
    private void backupPage(){content.addView(title("本地备份"));gap(content,14);LinearLayout box=card();box.addView(text(LocalBackup.status(this),14,GREEN));gap(box,8);box.addView(text("备份在手机公共文件夹中，卸载后仍保留。",13,MUTED));
        android.content.SharedPreferences prefs=LocalBackup.preferences(this);if(LocalBackup.configured(this)){gap(box,8);box.addView(text(prefs.getString("folder",""),12,MUTED));if(prefs.getBoolean("awaiting_restore",false)){box.addView(button("恢复历史备份",true,()->showLocalSnapshots()));}else{checkbox(box,"自动备份",LocalBackup.enabled(this),value->{prefs.edit().putBoolean("enabled",value).commit();if(value)LocalBackup.request(this);else androidx.work.WorkManager.getInstance(this).cancelUniqueWork("wengu-local-backup");render();});checkbox(box,"备份包含私密经验",prefs.getBoolean("include_private",true),value->{prefs.edit().putBoolean("include_private",value).remove("digest").commit();LocalBackup.request(this);render();});if(!prefs.getBoolean("include_private",true))box.addView(text("新备份排除私密经验；旧版本可能仍包含。",12,MUTED));
            box.addView(button("立即备份",true,()->runIO("正在备份",()->LocalBackup.write(this),()->render())));box.addView(button("查看本地备份",false,()->showLocalSnapshots()));}}
        box.addView(button(LocalBackup.configured(this)?"更换备份文件夹":"选择本地备份文件夹",!LocalBackup.configured(this),()->chooseBackupFolder()));hint(box,"建议在手机 Documents 内新建「温故备份」。保留最近 10 个完整版本，包含经验、进度、设置和照片。第一次选择文件夹后，保存经验会同步完成本地备份。重装后需要重新选择之前的文件夹。");
        content.addView(button("从备份文件恢复",false,()->{Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("*/*");startActivityForResult(intent,IMPORT_BACKUP);}));
    }
    private void chooseBackupFolder(){Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);intent.putExtra(android.provider.DocumentsContract.EXTRA_INITIAL_URI,Uri.parse("content://com.android.externalstorage.documents/document/primary%3ADocuments"));startActivityForResult(intent,PICK_BACKUP_FOLDER);}
    private void showLocalSnapshots(){runIO("正在读取本地备份",()->{List<LocalBackup.Snapshot> versions=LocalBackup.list(this);localSnapshots=versions;return versions.isEmpty()?"这个文件夹还没有温故备份":"找到 "+versions.size()+" 份本地备份";},()->{if(localSnapshots==null||localSnapshots.isEmpty())return;String[] names=new String[localSnapshots.size()];for(int i=0;i<names.length;i++)names[i]=localSnapshots.get(i).name;new AlertDialog.Builder(this).setTitle("选择要恢复的版本").setItems(names,(dialog,index)->inspectBackup(localSnapshots.get(index).uri)).setNegativeButton("取消",null).show();});}
    private List<LocalBackup.Snapshot> localSnapshots;
    private void inspectBackup(Uri uri){runIO("正在检查备份",()->{InputStream in=getContentResolver().openInputStream(uri);if(in==null)throw new IOException("无法读取备份");importPlan=Backup.inspect(this,in);return "备份检查通过";},()->showImport());}
    private String eventResult(JSONObject e){if("attempt".equals(e.optString("type")))return "开始生成并设置壁纸";String r=e.optString("result");switch(r){case "success":return "已完成";case "stage_advanced":return "已应用，并安排下一次展示";case "maintenance":return "已应用日常轮换内容";case "paused":return "自动展示已暂停";default:return r;}}
    private String eventLabel(String t){switch(t){case "attempt":return "尝试应用";case "delivered":return "应用成功";case "appearance":return "位置与样式应用";case "schedule_failed":return "后台任务未排入";case "failed":return "应用失败";case "saved":return "经验保存";case "restore":return "备份恢复";case "external_change":return "系统壁纸变化";default:return t;}}
    private void exportWallpaper(){if(styleDraft==null)return;JSONObject e=Store.find(state,detailId);if(e==null){message("请先保存一条经验，再导出壁纸");return;}int configuredTarget=styleDraft.optInt("target",2);final int exportTarget=configuredTarget==3?previewTarget:configuredTarget;runIO("正在生成图片",()->{int[] size=DeliveryEngine.size(this);exportBitmap=WallpaperComposer.render(this,e,styleDraft,size[0],size[1],exportTarget).bitmap;return "请选择图片保存位置";},()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/png");i.putExtra(Intent.EXTRA_TITLE,"温故壁纸.png");startActivityForResult(i,EXPORT_WALL);});}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){if(request==EXPORT_WALL&&exportBitmap!=null){exportBitmap.recycle();exportBitmap=null;}return;}Uri uri=data.getData();
        if(request==PICK_BACKUP_FOLDER){final int flags=data.getFlags();runIO("正在设置备份位置",()->{LocalBackup.configure(this,uri,flags);localSnapshots=LocalBackup.list(this);if(LocalBackup.preferences(this).getBoolean("awaiting_restore",false))return "找到历史备份，可恢复之前的经验";return LocalBackup.write(this);},()->{page="backup";render();if(LocalBackup.preferences(this).getBoolean("awaiting_restore",false))new AlertDialog.Builder(this).setTitle("找到之前的本地备份").setMessage("选择一个版本恢复经验。恢复前不会写入空白备份。").setPositiveButton("选择恢复版本",(dialog,which)->showLocalSnapshots()).setNegativeButton("稍后恢复",null).show();});}
        else if(request==PICK_PHOTO){String destination=photoDestination;runIO("正在保存照片副本",()->WallpaperComposer.importPhoto(this,uri),()->{} ,ref->{if("entry".equals(destination)){if(draft!=null){Store.put(draft,"photo",ref);Store.put(draft,"theme",-1);page="edit";}}else{if(styleDraft==null)styleDraft=Store.copy(Store.settings(state));Store.put(styleDraft,"photo",ref);Store.put(styleDraft,"random",false);page="style";}render();});}
        else if(request==EXPORT_BACKUP)runIO("正在导出备份",()->{OutputStream out=getContentResolver().openOutputStream(uri);if(out==null)throw new IOException("无法写入目标文件");Backup.export(this,out,includePrivate);return "备份已导出";},()->render());
        else if(request==IMPORT_BACKUP)inspectBackup(uri);
        else if(request==EXPORT_WALL)runIO("正在导出壁纸",()->{if(exportBitmap==null)throw new IOException("图片已失效，请重新导出");try(OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null||!exportBitmap.compress(Bitmap.CompressFormat.PNG,100,out))throw new IOException("图片保存失败");}finally{exportBitmap.recycle();exportBitmap=null;}return "壁纸图片已保存";},()->render());
    }
    private void showImport(){if(importPlan==null)return;String info="新增 "+importPlan.added+" 条，重复 "+importPlan.duplicates+" 条，冲突 "+importPlan.conflicts+" 条。\n恢复后自动展示保持暂停。";String[] choices={"冲突保留本机内容","冲突采用备份内容","冲突另存为新经验"};final int[] chosen={0};AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle("恢复备份").setMessage(info).setNegativeButton("取消",(d,w)->{importPlan.discard();importPlan=null;});if(importPlan.conflicts==0)dialog.setPositiveButton("恢复",(d,w)->restoreImport(0));else dialog.setPositiveButton("处理冲突",(d,w)->new AlertDialog.Builder(this).setTitle("冲突处理方式").setSingleChoiceItems(choices,0,(d2,index)->chosen[0]=index).setPositiveButton("恢复",(d2,w2)->restoreImport(chosen[0])).setNegativeButton("取消",(d2,w2)->{importPlan.discard();importPlan=null;}).show());dialog.show();}
    private void restoreImport(int mode){runIO("正在恢复",()->{Backup.restore(this,importPlan,mode);importPlan=null;LocalBackup.confirmRestore(this);return LocalBackup.afterSave(this,"备份已恢复，自动展示保持暂停");},()->{page="library";render();});}
    interface Work{String run()throws Exception;}
    interface StringResult{void accept(String result);}
    private void runIO(String label,Work work,Runnable done){runIO(label,work,done,null);}
    private void runIO(String label,Work work,Runnable done,StringResult consumer){if(busy)return;busy=true;ProgressDialog dialog=new ProgressDialog(this);dialog.setMessage(label);dialog.setCancelable(false);dialog.show();IO.execute(()->{String result;Exception error=null;try{result=work.run();if("正在保存".equals(label)||"正在保存样式".equals(label))result=LocalBackup.afterSave(this,result);}catch(Exception e){result="";error=e;}final String output=result;final Exception problem=error;runOnUiThread(()->{busy=false;if(isDestroyed()){return;}dialog.dismiss();if(problem!=null){message(problem.getMessage()==null?"操作未完成，请重试":problem.getMessage());return;}if(consumer!=null)consumer.accept(output);else Toast.makeText(this,output,Toast.LENGTH_LONG).show();done.run();});});}
    private void message(String value){if(!isDestroyed())new AlertDialog.Builder(this).setMessage(value).setPositiveButton("知道了",null).show();}
    private void hideKeyboard(){View v=getCurrentFocus();if(v!=null)((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);}
    private String targetLabel(int target){return target==1?"仅桌面":target==3?"锁屏和桌面":"仅锁屏";}
    private String statusLabel(JSONObject e){return e.optBoolean("private")?"私密":"paused".equals(e.optString("status"))?"已暂停":"archived".equals(e.optString("status"))?"已归档":e.optBoolean("important")?"重要 · 参与展示":"参与展示";}
    private String dueLabel(JSONObject e){return e.optInt("stage",-1)<0?"等待首次展示":"再次展示 "+LocalDate.ofEpochDay(e.optLong("due")).format(DateTimeFormatter.ofPattern("M月d日"));}
    private String dateTime(long t){return Instant.ofEpochMilli(t).atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("M月d日 HH:mm"));}
    private String tagsText(JSONArray tags){if(tags==null)return "";List<String> values=new ArrayList<>();for(int i=0;i<tags.length();i++)values.add(tags.optString(i));return android.text.TextUtils.join("，",values);}
    private void back(){if("edit".equals(page)){new AlertDialog.Builder(this).setTitle("保留这条草稿？").setPositiveButton("保留并返回",(d,w)->{getPreferences(MODE_PRIVATE).edit().putString("draft",draft.toString()).apply();page="library";render();}).setNegativeButton("放弃草稿",(d,w)->{draft=null;getPreferences(MODE_PRIVATE).edit().remove("draft").apply();page="library";render();}).show();}else if("style".equals(page)){styleDraft=null;page=detailId.isEmpty()?"settings":"detail";render();}else{page="data".equals(page)||"backup".equals(page)?"settings":"library";render();}}
    @Override public void onBackPressed(){if("today".equals(page))super.onBackPressed();else if("settings".equals(page)||"library".equals(page)){page="today";render();}else back();}
    abstract static class SimpleWatcher implements TextWatcher{public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){}}
}
